baseURL = "https://web3vclist.com/"
languageCode = "en-us"
title = "Web3 VC List - Blockchain & Crypto Venture Capitalists"

[params]
  description = "Curated directory of venture capital firms actively investing in Web3, blockchain, crypto, and decentralized technology startups"
  sector_filter = ["Web3", "Blockchain", "Crypto"]
  ga_id = "G-VWK29XZN8N"

[module]
  [[module.mounts]]
    source = "../../shared/content"
    target = "content"
  [[module.mounts]]
    source = "../../shared/layouts"
    target = "layouts"
  [[module.mounts]]
    source = "../../shared/static"
    target = "static"
  [[module.mounts]]
    source = "static"
    target = "static"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
[sitemap]
  changefreq = "weekly"
  priority = 0.5